version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: cms_affiliate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
